controller_names:
  - joint_trajectory_controller
  - hand_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7

hand_controller:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - finger_joint
